language: cpp
dist: trusty
sudo: required
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libboost-all-dev
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make all
